---
# Used for testing from local for now...
kind: Service
apiVersion: v1
metadata:
  name: mssql-mssql-linux-lb
spec:
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: mssql
  selector:
    app: mssql-linux
    release: mssql
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
...