---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: stunnel
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'stunnel:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'centos:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/cpitman/stunnel-openshift.git'
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
  runPolicy: Serial
...
